// DO NOT EDIT. This file is auto-generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `deno task dev`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/login.tsx";
import * as $2 from "./routes/dashboard.tsx";
import * as $3 from "./routes/mfa/verify.tsx";
import * as $4 from "./routes/api/auth/signin.ts";
import * as $5 from "./routes/api/auth/signup.ts";
import * as $6 from "./routes/api/mfa/verify.ts";
import * as $7 from "./routes/api/mfa/enroll.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/login.tsx": $1,
    "./routes/dashboard.tsx": $2,
    "./routes/mfa/verify.tsx": $3,
    "./routes/api/auth/signin.ts": $4,
    "./routes/api/auth/signup.ts": $5,
    "./routes/api/mfa/verify.ts": $6,
    "./routes/api/mfa/enroll.ts": $7,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
